# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Docker compose
      run: docker-compose -f docker-compose-v3.yml up -d --scale chrome=3 --scale firefox=3 --scale edge=1
    - name: Sleep for 60 seconds
      run: sleep 60s
      shell: bash
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Docker compose
      run: docker-compose -f docker-compose-v3.yml down
    - name: Submit results to Xray
      uses: mikepenz/xray-action@v3.0.4
      with:
        username: ${{ secrets.client_id }}
        password: ${{ secrets.client_secret }}
        testFormat: "testng"
        testPaths: "**/surefire-reports/*.xml"
        projectKey: "JON"
        testPlanKey: "JON-2816"  
        testEnvironments: "preproduccion"
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: target/surefire-reports/*.*
 
  deploydev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Development
        run: echo app deployed en dev

  approve:
      needs: deploydev
      runs-on: ubuntu-latest
      steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: juananmora
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
  
  testdev:
    needs: approve
    runs-on: ubuntu-latest
    steps:
      - name: Test Deployment
        run: echo app deployed en dev
     
  deploypre:
    needs: deploydev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PRE
        run: echo app deployed en PRE

  deploypro:
    needs: deploypre
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PRO
        run: echo app deployed en PRO

            
   
    
